dash/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('visual/', include('visual.urls'))
]

visual/urls.py
from django.urls import path
from . import views

app_name = 'visual'  # 这句是必须的，和之后所有的URL语句有关
urlpatterns = [
    path('alert', views.alert, name="alert"),
    path('index', views.index, name='index'),
    path(r'query', views.query, name="query"),
    path(r'query1', views.query1, name="query1"),
    path('blog', views.blog, name = 'blog'),
    path('overview', views.overview, name = 'overview'),
    path(r'showdata', views.showdata, name="showdata"),
    path(r'plot', views.plot, name="plot"),
    path(r'get_process_name', views.get_process_name),


]

visual/models.py
from django.db import models

# Create your models here.

visual/views.py
import re
import datetime
from ydata_profiling import ProfileReport
import csaps
from django.http import HttpResponse
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import os
from django.shortcuts import render, redirect
import json
from .charts import *
try:
    import six
except ImportError:
    from django.utils import six
import time
import json
from random import randrange
from django.http import HttpResponse
from django.template.defaulttags import register
# from rest_framework.views import APIView
root_path = './'
source_path = 'C:/Users/1000300246/Desktop/test_folder/'
target_path = 'C:/Users/sas053/Desktop/dataset'


global DF
DF = pd.read_csv('C:/Users/1000300246/Desktop/test_folder/HDD_Magnetic.csv')
# DF.sort_values(by=['new_Date'], ascending=True, inplace=True)
@register.filter
def get_range(value):
    return range(len(value))

def test_read_speed():
    since = time.time()
    print('it costs: ', time.time() - since, 's to load the file')
    print(DF.memory_usage().sum() / (1024 ** 2), 'MB')
    since = time.time()
    df_col = DF.iloc[:, 7]
    print('it costs: ', time.time() - since, 's to load the column')


def read_data(source_path, target_path, file_name, file_name_save):
    source_file = source_path + file_name
    target_file = target_path + file_name_save
    if source_file.endswith('.sas7bdat'):
        df = pd.read_sas(source_file)
    # elif source_file.endswith('.jmp'):
    #     jmp = Dispatch("JMP.Application")
    #     doc = jmp.OpenDocument(source_file)
    #     # temporarily add csv file
    #     doc.SaveAs(target_file)
    #     df = pd.read_csv(target_file)
    #     # Delete the extraly generated csv file 
    #     # to ensure that the data warehouse has not changed
    #     os.remove(target_path + file_name_save)
    else:
        df = pd.read_csv(source_file)
    return df


def get_kpi(df, column, axis=0):
    df = df.loc[:, [column]]

    try:
        df_mean = df.mean(axis)[0]
        df_std = df.std(axis)[0]
        df_median = df.median(axis)[0]
    except:
        df_mean = 'N/A'
        df_std = 'N/A'
        df_median = 'N/A'
    return {
        "df_mean": df_mean,
        "df_std": df_std,
        "df_median": df_median,
    }


# 该字典key为前端准备显示的所有多选字段名, value为数据库对应的字段名
D_MULTI_SELECT = {
    'YC': ['Yield', 'EC'],
    'Magnetic': ['ACC', 'MCW', 'Roller SER'],
    'Reader HI': ['1k-BEM(Rd)NT', '1k-BEM(Rd)HT', 'Bi-state XTI Profile (writer induced HI)', '172c'],
    'PE': ['PE NT (Degauss on)', 'PE HT (Degauss off/on)'],
    'XTI': ['XTI NT', 'XTI HT'],
    'XTI Degradation': ['Delta XTI', 'Delta OWC'],
    'Writer instability': ['1K-BEM (WrRd) HT', 'RV_Range', 'B_Allband'],
    'Writer degradation': ['Delta MCW', 'Delta SER', 'Delta OW'],
    'Write-short': ['UEC (S5W, Func, SRST, Fin & Featuring)'],
}
ALERT_PARAMETER = {
    'Write-Short': ['F61F_DPPM', 'F623_DPPM(PCM)'],
    'Reader HI': ['Bi_state', 'hi_idd_sig_P99_rd_HT_2R', 'i_rd_172c_cnt_p99'],
    'PE': ['R_delta_PE_p99', 'R_delSER_Max_P99_HT_Track0', 'R_delSER_Max_P99_NT_Track0'],
    'XTI': ['R_delSER_Max_P99_HT_F_FTI', 'R_delSER_Max_P99_HT_N_FTI', 'R_delSER_Max_P99_HT_NTI', 'R_delSER_Max_P99_HT_Track23', 'R_delSER_Max_P99_HT_Trackminus1', 'R_delSER_Max_P99_HT_Trackplus1', 'nmax50byband_6600_min_P1'],
    'XTI Degradation': ['dNTI_FR', 'OWC_delta_min_P1'],
    'Writer Instability': ['hi_idd_sig_P99_wr_HT_trim', 'hi_idd_sig_P99_wr_HT_nontrim', 'RV_Rng_P99', 'B_byallband_P1'],
    'Writer Degradation': ['Final_SER_delta_P99', 'MCW_MD_delta_P99', 'OWP_delta_min_P1']
}
def index(request):
    mselect_dict = {}
    dic = {}
    form_dict = dict(six.iterlists(request.GET))
    # print('arrive index!', form_dict)
    df = DF
    dct = columns2dictionary(df)
    for key, value in dct.items():
        mselect_dict[key] = {}
        mselect_dict[key]['select'] = value
        mselect_dict[key]['options'] = get_distinct_list(df, value)  # 以后可以后端通过列表为每个多选控件传递备选项
        dic[key] = list(set(get_distinct_list(df, value).tolist()))
    # print('mselect_dict', mselect_dict)
    context = {
        'mselect_dict': mselect_dict,
        'D_MULTI_SELECT': D_MULTI_SELECT,
        'ALERT_PARAMETER': ALERT_PARAMETER,
        'Product': dic['PRODUCT'],
        'Model': dic['HDD_Model'],
        'option_list': list(ALERT_PARAMETER.keys())
    }
    # 下面一定要返回子模板，否则的话是block与endblock失效的原因！！！
    return render(request, 'visual/plot.html', context)

def find_category(string):
  for key, value in ALERT_PARAMETER.items():
    for v in value:
      if v in string:
        return key

def alert(request):
    dic1 = {'a':[{'wafer':110,'feature':'dvnj'},{'wafer':110,'feature':'dvnj'},{'wafer':110,'feature':'dvnj'}],
            'b':[{'wafer':111,'feature':'dfve'},{'wafer':110,'feature':'dvnj'}]}
    form_dict = dict(six.iterlists(request.GET))
    new_dict = {key: ALERT_PARAMETER[key] for key in ALERT_PARAMETER}
    for i in new_dict:
        new_dict[i] = []
    df = pd.read_csv(source_path + 'wafer_table.csv')
    for i in range(len(df)):
        tmp = {}
        tmp['wafernum'] = df.iloc[i]['wafernum']
        tmp['feature'] = df.iloc[i]['feature']
        tmp['value'] = df.iloc[i]['value']
        tmp['hdd_model'] = df.iloc[i]['hdd_model']
        category = find_category(df.iloc[i]['feature'])
        new_dict[category].append(tmp)
    # alert_df = df[df['outlier'] == 1][['Product', 'HDD_Model', 'Head_Site', 'Disk', 'wafernum', 'parameter_name']]
    # dat = []
    # for i, j in alert_df.iterrows():
    #     j = dict(j)
    #     j['raw_index'] = i
    #     dat.append(j)
    context = {
        'data': new_dict
    }
    # for i in new_dict:
    #     print(i)
    #     for j in new_dict[i]:
    #         print(j['wafernum'], j['feature'], j['value'], j['hdd_model'])
    #     print('--------------')


    return render(request, 'alert/alert.html', context)


def columns2dictionary(df):
    """
    该字典key为前端准备显示的所有多选字段名, value为数据库对应的字段名
    从DataFrame里读取生成, key即是value, 所见即所得
    """
    dictionary = {col: col for col in df.columns}

    return dictionary


def get_distinct_list(df, column):
    """
    获取一个feature下的不同的值，通过unique()函数
    改list返回可作为画图中的legend
    """
    # print(df[column].unique())
    l = df[column].unique()
    return l


def search(request, column, kw, df):
    try:
        df = df
        l = df.values.flatten().tolist()
        results_list = []
        for element in l:
            option_dict = {'name': element,
                           'value': element,
                           }
            results_list.append(option_dict)
        res = {
            "success": True,
            "results": results_list,
            "code": 200,
        }
    except Exception as e:
        res = {
            "success": False,
            "errMsg": e,
            "code": 0,
        }
    return HttpResponse(json.dumps(res, ensure_ascii=False),
                        content_type="application/json charset=utf-8")  # 返回结果必须是json格式


def choose_file(request):
    file_list_dict = dict(six.iterlists(request.GET))
    file_list = os.path()
    return file_list


def showdata(request, df=DF):
    # data = dict(six.iterlists(request.GET))
    con = {
        'alldata': df.to_html(),
    }
    return HttpResponse(json.dumps(con, ensure_ascii=False),
                        content_type="application/json charset=utf-8")


def query(request, data=DF):
    form_dict = dict(six.iterlists(request.GET))
    print('query', form_dict)
    df = data
    # box = []
    if form_dict:
        global x_feature, y_feature, box
        x_feature = form_dict['Feature1'][0]
        y_feature = form_dict['Feature2'][0]
        box = [x_feature, y_feature]
        multi_con = form_dict['Feature_opt[]']
        for i in multi_con:
            box.append(i)
        kpi = get_kpi(df, x_feature)
        df = df.loc[:, box]
    box_df = pd.DataFrame(df)
    print('aaaaaaa', x_feature, y_feature, kpi)
    context = {
        "df_mean": kpi["df_mean"],
        "df_std": kpi["df_std"],
        "df_median": kpi["df_median"],
        'data': df.to_html(),
        'data_': box_df.to_html(),
    }
    return HttpResponse(json.dumps(context, ensure_ascii=False),
                        content_type="application/json charset=utf-8")  # 返回结果必须是json格式


def query1(request, data=DF):
    form_dict = dict(six.iterlists(request.GET))
    print('query1', form_dict)
    if form_dict:
        global process_choose, query1_data
        process_choose = str(form_dict['process_choose[]'][0])
        print('process_choose', process_choose)
        query1_data = DF[DF['Process'] == process_choose]
    context = {
        "process_choose": 1,
        "query1_data": query1_data.to_json(),
    }
    return HttpResponse(json.dumps(context, ensure_ascii=False),
                        content_type="application/json charset=utf-8")  # 返回结果必须是json格式


def plot(request):
    type = list(dict(six.iterlists(request.GET)).keys())[0]
    # item = dict(six.iterlists(request.GET)).keys()
    print('===============', type, '==================')

    if type == 'Combine':
        chart = echarts_barline(DF, x_feature, y_feature, box)
    elif type == 'Line':
        chart = echarts_myline(DF, x_feature, y_feature, box)
    elif type == 'Stack':
        chart = echarts_stackbar(DF, x_feature, y_feature, box)

    elif type == 'Plot':
        chart = page_simple_layout()
        # chart = echarts_two_test(query1_data, process_choose)

    chart = chart.dump_options()

    total_trend = json.loads(chart)
    # print('total_trend', type(total_trend))
    context = {
        'total_trend': total_trend,
    }
    return HttpResponse(json.dumps(context, ensure_ascii=False),
                        content_type="application/json charset=utf-8")


def blog(request):
    mselect_dict = {}
    form_dict = dict(six.iterlists(request.GET))
    df = DF.iloc[0:50]
    dct = columns2dictionary(df)
    for key, value in dct.items():
        mselect_dict[key] = {}

visual/templates/visual/base.html
<!-- 载入静态文件 更早版本可能会用load staticfiles -->
{% load static %}
<!--<!DOCTYPE html>-->
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <title>数据分析</title>
    <link rel="stylesheet" href="{% static 'datatables/dataTables.semanticui.min.css' %}">
    <link rel="stylesheet" href="{% static 'Semantic-UI-CSS-master/semantic.min.css' %}">
    <script src="{% static 'jquery/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'datatables/dataTables.semanticui.min.js' %}"></script>
    <!-- <script src="{% static 'datatables/percentageBars.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'Semantic-UI-CSS-master/semantic.js' %}"></script>
    <script src="{% static 'echarts/echarts.min.js' %}"></script>
    <!-- <script src="{% static 'echarts/china.js' %}"></script> -->
</head>



<body>

<!-- 引入导航栏 -->
{% include 'visual/header.html' %}
<!-- 预留具体页面的位置 -->
{% block body %}{% endblock body %}
<!-- 引入注脚 -->
<!--{% include 'visual/footer.html' %}-->

</body>

</html>

visual/templates/visual/blog.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "visual/base.html" %}

<div class="ui tab segment active" data-tab="Algorithm">

<!-- 隐藏分隔条 -->
<div class="ui hidden divider"></div>

<!-- 写入 base.html 中定义的 body content -->

{% block body %}
<!-- 因为semantic ui的特性需要在body部分写个pusher避免内容被顶部导航栏遮挡 -->
<div id="Algorithm" class="pusher" style="padding-top:50px" data-tab="Algorithm">
    {{ data }}
    <div class="ui celled grid">
        <!-- 左边3/16为filter页面, include -->
        <div class="six wide column">
            {% include 'visual/filter.html' %}
        </div>

        <!-- 右边13/16为display页面, 预留block -->
        <div class="ten wide column">
            {% block blog_main_display %}{% endblock blog_main_display %}
        </div>
    </div>
</div></div>

{% endblock body %}

visual/templates/visual/blog_main_display.html
{% extends "visual/blog.html" %}
{% block blog_main_display %}


<!-- 创建Semantic UI tab，根据鼠标点击切换，以保证页面干净清爽 -->

<div class="ui pointing secondary menu">
    <a class="item" data-tab="Plot"><i class="circle icon"></i>Plot</a>
    <a class="item active" data-tab="Summary"><i class="circle icon"></i>Summary</a>
    <a class="item" data-tab="Analysis"><i class="circle icon"></i>Analysis</a>
</div>

<div class="ui tab segment active" data-tab="Summary">

    <!-- 数据处理时的loading遮罩 -->
    <div class="ui active dimmer" id="dimmer">
    <div class="ui text" style="color: #ffffff">
        请使用左侧筛选框选择两个维度生成图像(分析维度)
        <br><br>
        选择若干个维度在图中填充辅助信息(辅助维度)
    </div>
    </div>

    <h3 class="ui header">
        <div class="content">
            KPIs
            <div class="sub header">KPIs, containing mean, std, median of input feature</div>
        </div>
    </h3>

    <div class="ui divider"></div>

    <div class="sub header">Feature 1</div>

    <!-- Semantic UI的statistic类能呈现“醒目大数字”的效果 -->
    <div class="ui small three statistics">

        <div class="statistic">
            <div class="value" id="df_mean">
                {{ df_mean }}
            </div>
            <div class="label" id="df_mean_print">
                df_mean
            </div>
        </div>

        <div class="statistic">
            <div class="value" id="df_std">
                {{ df_std }}
            </div>
            <div class="label" id = 'df_std_print'>
                df_std
            </div>
        </div>

        <div class="statistic">
            <div class="value" id="df_median">
                {{ df_median }}
            </div>
            <div class="label" id="df_median_print">
                df_median
            </div>
        </div>

    </div>

    <div class="ui divider"></div>


    <div class="sub header">Feature 2</div>

    <!-- Semantic UI的statistic类能呈现“醒目大数字”的效果 -->
    <div class="ui small three statistics">

        <div class="statistic">
            <div class="value" id="df_mean1">
                {{ df_mean }}
            </div>
            <div class="label" id="df_mean_print">
                df_mean
            </div>
        </div>

        <div class="statistic">
            <div class="value" id="df_std1">
                {{ df_std }}
            </div>
            <div class="label" id = 'df_std_print'>
                df_std
            </div>
        </div>

        <div class="statistic">
            <div class="value" id="df_median1">
                {{ df_median }}
            </div>
            <div class="label" id="df_median_print">
                df_median
            </div>
        </div>

    </div>
    
</div>

<div class="ui tab segment" data-tab="Analysis">

    <h3 class="ui header">
        <div class="content">
            DataFrame (dataTables)
            <div class="sub header">数据表格</div>
        </div>
    </h3>

    <div class="ui divider"></div>

    <div class="ui container" id='data' style="width: 100%; overflow-x: scroll; overflow-y: hidden;">
        <!-- Django渲染html代码时需要加入|safe，保证html不会被自动转义 -->
        {{ data|safe }}
    </div>

</div>


<div class="ui tab segment" data-tab="Plot">
    <h3 class="ui header">
        <div class="content">
            Figure
            <div class="sub header">柱状折线复合图</div>
        </div>
    </h3>
    <div class="ui divider"></div>
    <div class="ui container">
        <div id="figure_space" style="width:1000px; height:600px;"></div>
    </div>
</div>




<!-- 下方js为保证Semantic UI tab类工作 -->
<script>
    $('.pointing.secondary.menu .item').tab();
</script>

{% endblock %}

visual/templates/visual/display.html
{% extends "visual/analysis.html" %}
{% block display %}
{% load static %}
<!-- 创建2个Semantic UI tab，根据鼠标点击切换，以保证页面干净清爽 -->
<div class="ui pointing secondary menu">
    <a class="item" data-tab="Summary"><i class="circle icon"></i>Summary</a>
    <a class="item" data-tab="Feature"><i class="trophy icon"></i>Feature</a>
    <a class="item" data-tab="show_all"><i class="circle icon"></i>show_all</a>
    <a class="item active" data-tab="plot"><i class="circle icon"></i>plot</a>
</div>

<div class="ui tab segment" data-tab="Summary">
    <!-- 数据处理时的loading遮罩 -->
    <div class="ui active dimmer" id="dimmer">
        <div class="ui text" style="color: #ffffff">
            请使用左侧筛选框选择两个维度生成图像(分析维度)
            <br><br>
            选择若干个维度在图中填充辅助信息(辅助维度)
        </div>
    </div>

    <h3 class="ui header">
        <div class="content">
            KPIs
            <div class="sub header">KPIs, containing mean, std, median of input feature</div>
        </div>
    </h3>

    <div class="ui divider"></div>

    <div class="sub header">Feature 1</div>
    <!-- Semantic UI的statistic类能呈现“醒目大数字”的效果 -->
    <div class="ui small three statistics">
        <div class="statistic">
            <div class="value" id="df_mean">
                {{ df_mean }}
            </div>
            <div class="label" id="df_mean_print_1">
                df_mean
            </div>
        </div>
        <div class="statistic">
            <div class="value" id="df_std">
                {{ df_std }}
            </div>
            <div class="label" id = 'df_std_print_1'>
                df_std
            </div>
        </div>
        <div class="statistic">
            <div class="value" id="df_median">
                {{ df_median }}
            </div>
            <div class="label" id="df_median_print_1">
                df_median
            </div>
        </div>
    </div>
    <div class="ui divider"></div>
    <div class="sub header">Feature 2</div>
    <!-- Semantic UI的statistic类能呈现“醒目大数字”的效果 -->
    <div class="ui small three statistics">
        <div class="statistic">
            <div class="value" id="df_mean1">
                {{ df_mean }}
            </div>
            <div class="label" id="df_mean_print_2">
                df_mean
            </div>
        </div>
        <div class="statistic">
            <div class="value" id="df_std1">
                {{ df_std }}
            </div>
            <div class="label" id = 'df_std_print_2'>
                df_std
            </div>
        </div>
        <div class="statistic">
            <div class="value" id="df_median1">
                {{ df_median }}
            </div>
            <div class="label" id="df_median_print_2">
                df_median
            </div>
        </div>
    </div>
</div>

<div class="ui tab segment" data-tab="Feature">
    <h3 class="ui header">
        <div class="content">
            Selected Feature (ALL)
            <div class="sub header">所选特征</div>
        </div>
    </h3>
    <div class="ui divider"></div>
    <div class="ui container" id='data_' style="width: 100%; overflow-x: scroll; overflow-y: hidden;">
        <!-- Django渲染html代码时需要加入|safe，保证html不会被自动转义 -->
        {{ data_|safe }}
    </div>
    <div class="ui container" id='data_1' style="width: 100%; overflow-x: scroll; overflow-y: hidden;">
        <!-- Django渲染html代码时需要加入|safe，保证html不会被自动转义 -->
        {{ Feature_opt|safe }}
    </div>
</div>

<div class="ui tab segment" data-tab="show_all">
    <h3 class="ui header">
        <div class="content">
            Raw Data
            <div class="sub header">数据展示</div>
        </div>
    </h3>
    <div class="ui divider"></div>
    <div class="ui container" id='alldata' style="width: 100%; overflow-x: scroll; overflow-y: hidden;">
        {{ alldata|safe }}
    </div>
</div>

<div class="ui tab segment active" data-tab="plot">
    {% block plot %}{% endblock %}
</div>


<!-- 下方js为保证Semantic UI tab类工作 -->
<script>
    $('.pointing.secondary.menu .item').tab();
</script>



<script type="text/javascript">
    $("#plot_stack").click(function (event) {
        event.preventDefault();
        var chart = echarts.init(document.getElementById('total_trend'), 'white', {renderer: 'canvas'});
        $.ajax({
            url: '{% url 'visual:plot' %}',
            type: 'GET',
            data: 'Stack',
            success: function(ret) {
                chart.clear();
                chart.setOption(ret['total_trend']);
                chart.hideLoading();
            },
            error: function() {
                console.log('failure')
            }
        });
    })

    $("#plot_line").click(function (event) {
        event.preventDefault();
        var chart = echarts.init(document.getElementById('total_trend'), 'white', {renderer: 'canvas'});
        $.ajax({
            url: '{% url 'visual:plot' %}',
            type: 'GET',
            data: 'Line',
            success: function(ret) {
                chart.clear();
                chart.setOption(ret['total_trend']);
                chart.hideLoading();
            },
            error: function() {
                console.log('failure')
            }
        });
    })

    $("#plot_combine").click(function (event) {
        event.preventDefault();
        var chart = echarts.init(document.getElementById('total_trend'), 'white', {renderer: 'canvas'});
        $.ajax({
            url: '{% url 'visual:plot' %}',
            type: 'GET',
            data: 'Combine',
            success: function(ret) {
                chart.clear();
                chart.setOption(ret['total_trend']);
                chart.hideLoading();
            },
            error: function() {
                console.log('failure')
            }
        });
    })

    $("#plot_next").click(function (event) {
        event.preventDefault();
        var chart = echarts.init(document.getElementById('total_trend'), 'white', {renderer: 'canvas'});
        $.ajax({
            url: '{% url 'visual:plot' %}',
            type: 'GET',
            data: 'Plot',
            success: function(ret) {
                chart.clear();
                chart.setOption(ret['total_trend']);
                chart.hideLoading();
            },
            error: function() {
                console.log('failure')
            }
        });
    })
<!--    $("#return_index").click(function (event) {-->
<!--        event.preventDefault();-->
<!--        alert('重新选择按钮生效！');-->
<!--        $.ajax({-->
<!--            url: '{% url 'visual:index' %}'-->
<!--            type: 'GET',-->
<!--            data: 'Plot',-->
<!--            success: function(ret) {-->
<!--                chart.clear();-->
<!--                chart.setOption(ret['total_trend']);-->
<!--                chart.hideLoading();-->
<!--            },-->
<!--            error: function() {-->
<!--                console.log('failure')-->
<!--            }-->
<!--        });-->
<!--    })-->
</script>
{% endblock %}

visual/templates/visual/footer.html
<div class="ui inverted vertical footer segment">
    <div class="ui center aligned container">
        Footer 页尾
    </div>
</div>

visual/templates/visual/header.html
<div class="ui inverted menu">
<!-- <div class="ui pointing menu"> -->
    <div class="ui container">
        <a class="red item" data-tab="HomePage" href={% url 'visual:index' %} >&nbsp;&nbsp;&nbsp;&nbsp;首页 HomePage&nbsp;&nbsp;&nbsp;&nbsp;</a>
        <a class="orange item" data-tab="Algorithm" href={% url 'visual:blog' %} >&nbsp;&nbsp;&nbsp;&nbsp;算法分享 Blogs&nbsp;&nbsp;&nbsp;&nbsp;</a>
    </div>
</div>

<!-- <div class="ui pointing secondary menu">
    <a class="item" data-tab="Plot"><i class="circle icon"></i>Plot</a>
    <a class="item active" data-tab="Summary"><i class="circle icon"></i>Summary</a>
    <a class="item" data-tab="Analysis"><i class="circle icon"></i>Analysis</a>
</div> -->

visual/templates/visual/index.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "visual/base.html" %}

<!-- 隐藏分隔条 -->
<div class="ui hidden divider"></div>

<!-- 写入 base.html 中定义的 body content -->
{% block body %}
<!-- 因为semantic ui的特性需要在body部分写个pusher避免内容被顶部导航栏遮挡 -->
<div id="pusher" class="pusher" style="padding-top:50px">
    {{ data }}
</div>
{% endblock body %}

visual/templates/visual/static.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

html {
    margin: 0;
    min-height: 978px;
    height: auto !important;
    height: 978px;
}
body {
	height: 100%;
	min-width: 100%;
	min-height: 978px;
	margin:0;
	font-family: Arial;
	padding: 10px;
	background: #f1f1f1;
}