dash/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('visual/', include('visual.urls'))
]

visual/urls.py
from django.urls import path
from . import views

app_name = 'visual'  # 这句是必须的，和之后所有的URL语句有关
urlpatterns = [
    path('alert', views.alert, name="alert"),
    path('index', views.index, name='index'),
    path(r'query', views.query, name="query"),
    path(r'query1', views.query1, name="query1"),
    path('blog', views.blog, name = 'blog'),
    path('overview', views.overview, name = 'overview'),
    path(r'showdata', views.showdata, name="showdata"),
    path(r'plot', views.plot, name="plot"),
    path(r'get_process_name', views.get_process_name),


]

visual/models.py
from django.db import models

# Create your models here.

visual/views.py
import re
import datetime
from ydata_profiling import ProfileReport
import csaps
from django.http import HttpResponse
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import os
from django.shortcuts import render, redirect
import json
from .charts import *
try:
    import six
except ImportError:
    from django.utils import six
import time
import json
from random import randrange
from django.http import HttpResponse
from django.template.defaulttags import register
# from rest_framework.views import APIView
root_path = './'
source_path = 'C:/Users/1000300246/Desktop/test_folder/'
target_path = 'C:/Users/sas053/Desktop/dataset'


global DF
DF = pd.read_csv('C:/Users/1000300246/Desktop/test_folder/HDD_Magnetic.csv')
# DF.sort_values(by=['new_Date'], ascending=True, inplace=True)
@register.filter
def get_range(value):
    return range(len(value))

def test_read_speed():
    since = time.time()
    print('it costs: ', time.time() - since, 's to load the file')
    print(DF.memory_usage().sum() / (1024 ** 2), 'MB')
    since = time.time()
    df_col = DF.iloc[:, 7]
    print('it costs: ', time.time() - since, 's to load the column')


def read_data(source_path, target_path, file_name, file_name_save):
    source_file = source_path + file_name
    target_file = target_path + file_name_save
    if source_file.endswith('.sas7bdat'):
        df = pd.read_sas(source_file)
    # elif source_file.endswith('.jmp'):
    #     jmp = Dispatch("JMP.Application")
    #     doc = jmp.OpenDocument(source_file)
    #     # temporarily add csv file
    #     doc.SaveAs(target_file)
    #     df = pd.read_csv(target_file)
    #     # Delete the extraly generated csv file 
    #     # to ensure that the data warehouse has not changed
    #     os.remove(target_path + file_name_save)
    else:
        df = pd.read_csv(source_file)
    return df


def get_kpi(df, column, axis=0):
    df = df.loc[:, [column]]

    try:
        df_mean = df.mean(axis)[0]
        df_std = df.std(axis)[0]
        df_median = df.median(axis)[0]
    except:
        df_mean = 'N/A'
        df_std = 'N/A'
        df_median = 'N/A'
    return {
        "df_mean": df_mean,
        "df_std": df_std,
        "df_median": df_median,
    }


# 该字典key为前端准备显示的所有多选字段名, value为数据库对应的字段名
D_MULTI_SELECT = {
    'YC': ['Yield', 'EC'],
    'Magnetic': ['ACC', 'MCW', 'Roller SER'],
    'Reader HI': ['1k-BEM(Rd)NT', '1k-BEM(Rd)HT', 'Bi-state XTI Profile (writer induced HI)', '172c'],
    'PE': ['PE NT (Degauss on)', 'PE HT (Degauss off/on)'],
    'XTI': ['XTI NT', 'XTI HT'],
    'XTI Degradation': ['Delta XTI', 'Delta OWC'],
    'Writer instability': ['1K-BEM (WrRd) HT', 'RV_Range', 'B_Allband'],
    'Writer degradation': ['Delta MCW', 'Delta SER', 'Delta OW'],
    'Write-short': ['UEC (S5W, Func, SRST, Fin & Featuring)'],
}
ALERT_PARAMETER = {
    'Write-Short': ['F61F_DPPM', 'F623_DPPM(PCM)'],
    'Reader HI': ['Bi_state', 'hi_idd_sig_P99_rd_HT_2R', 'i_rd_172c_cnt_p99'],
    'PE': ['R_delta_PE_p99', 'R_delSER_Max_P99_HT_Track0', 'R_delSER_Max_P99_NT_Track0'],
    'XTI': ['R_delSER_Max_P99_HT_F_FTI', 'R_delSER_Max_P99_HT_N_FTI', 'R_delSER_Max_P99_HT_NTI', 'R_delSER_Max_P99_HT_Track23', 'R_delSER_Max_P99_HT_Trackminus1', 'R_delSER_Max_P99_HT_Trackplus1', 'nmax50byband_6600_min_P1'],
    'XTI Degradation': ['dNTI_FR', 'OWC_delta_min_P1'],
    'Writer Instability': ['hi_idd_sig_P99_wr_HT_trim', 'hi_idd_sig_P99_wr_HT_nontrim', 'RV_Rng_P99', 'B_byallband_P1'],
    'Writer Degradation': ['Final_SER_delta_P99', 'MCW_MD_delta_P99', 'OWP_delta_min_P1']
}
def index(request):
    mselect_dict = {}
    dic = {}
    form_dict = dict(six.iterlists(request.GET))
    # print('arrive index!', form_dict)
    df = DF
    dct = columns2dictionary(df)
    for key, value in dct.items():
        mselect_dict[key] = {}
        mselect_dict[key]['select'] = value
        mselect_dict[key]['options'] = get_distinct_list(df, value)  # 以后可以后端通过列表为每个多选控件传递备选项
        dic[key] = list(set(get_distinct_list(df, value).tolist()))
    # print('mselect_dict', mselect_dict)
    context = {
        'mselect_dict': mselect_dict,
        'D_MULTI_SELECT': D_MULTI_SELECT,
        'ALERT_PARAMETER': ALERT_PARAMETER,
        'Product': dic['PRODUCT'],
        'Model': dic['HDD_Model'],
        'option_list': list(ALERT_PARAMETER.keys())
    }
    # 下面一定要返回子模板，否则的话是block与endblock失效的原因！！！
    return render(request, 'visual/plot.html', context)

def find_category(string):
  for key, value in ALERT_PARAMETER.items():
    for v in value:
      if v in string:
        return key

def alert(request):
    dic1 = {'a':[{'wafer':110,'feature':'dvnj'},{'wafer':110,'feature':'dvnj'},{'wafer':110,'feature':'dvnj'}],
            'b':[{'wafer':111,'feature':'dfve'},{'wafer':110,'feature':'dvnj'}]}
    form_dict = dict(six.iterlists(request.GET))
    new_dict = {key: ALERT_PARAMETER[key] for key in ALERT_PARAMETER}
    for i in new_dict:
        new_dict[i] = []
    df = pd.read_csv(source_path + 'wafer_table.csv')
    for i in range(len(df)):
        tmp = {}
        tmp['wafernum'] = df.iloc[i]['wafernum']
        tmp['feature'] = df.iloc[i]['feature']
        tmp['value'] = df.iloc[i]['value']
        tmp['hdd_model'] = df.iloc[i]['hdd_model']
        category = find_category(df.iloc[i]['feature'])
        new_dict[category].append(tmp)
    # alert_df = df[df['outlier'] == 1][['Product', 'HDD_Model', 'Head_Site', 'Disk', 'wafernum', 'parameter_name']]
    # dat = []
    # for i, j in alert_df.iterrows():
    #     j = dict(j)
    #     j['raw_index'] = i
    #     dat.append(j)
    context = {
        'data': new_dict
    }
    # for i in new_dict:
    #     print(i)
    #     for j in new_dict[i]:
    #         print(j['wafernum'], j['feature'], j['value'], j['hdd_model'])
    #     print('--------------')


    return render(request, 'alert/alert.html', context)


def columns2dictionary(df):
    """
    该字典key为前端准备显示的所有多选字段名, value为数据库对应的字段名
    从DataFrame里读取生成, key即是value, 所见即所得
    """
    dictionary = {col: col for col in df.columns}

    return dictionary


def get_distinct_list(df, column):
    """
    获取一个feature下的不同的值，通过unique()函数
    改list返回可作为画图中的legend
    """
    # print(df[column].unique())
    l = df[column].unique()
    return l


def search(request, column, kw, df):
    try:
        df = df
        l = df.values.flatten().tolist()
        results_list = []
        for element in l:
            option_dict = {'name': element,
                           'value': element,
                           }
            results_list.append(option_dict)
        res = {
            "success": True,
            "results": results_list,
            "code": 200,
        }
    except Exception as e:
        res = {
            "success": False,
            "errMsg": e,
            "code": 0,
        }
    return HttpResponse(json.dumps(res, ensure_ascii=False),
                        content_type="application/json charset=utf-8")  # 返回结果必须是json格式


def choose_file(request):
    file_list_dict = dict(six.iterlists(request.GET))
    file_list = os.path()
    return file_list


def showdata(request, df=DF):
    # data = dict(six.iterlists(request.GET))
    con = {
        'alldata': df.to_html(),
    }
    return HttpResponse(json.dumps(con, ensure_ascii=False),
                        content_type="application/json charset=utf-8")


def query(request, data=DF):
    form_dict = dict(six.iterlists(request.GET))
    print('query', form_dict)
    df = data
    # box = []
    if form_dict:
        global x_feature, y_feature, box
        x_feature = form_dict['Feature1'][0]
        y_feature = form_dict['Feature2'][0]
        box = [x_feature, y_feature]
        multi_con = form_dict['Feature_opt[]']
        for i in multi_con:
            box.append(i)
        kpi = get_kpi(df, x_feature)
        df = df.loc[:, box]
    box_df = pd.DataFrame(df)
    print('aaaaaaa', x_feature, y_feature, kpi)
    context = {
        "df_mean": kpi["df_mean"],
        "df_std": kpi["df_std"],
        "df_median": kpi["df_median"],
        'data': df.to_html(),
        'data_': box_df.to_html(),
    }
    return HttpResponse(json.dumps(context, ensure_ascii=False),
                        content_type="application/json charset=utf-8")  # 返回结果必须是json格式


def query1(request, data=DF):
    form_dict = dict(six.iterlists(request.GET))
    print('query1', form_dict)
    if form_dict:
        global process_choose, query1_data
        process_choose = str(form_dict['process_choose[]'][0])
        print('process_choose', process_choose)
        query1_data = DF[DF['Process'] == process_choose]
    context = {
        "process_choose": 1,
        "query1_data": query1_data.to_json(),
    }
    return HttpResponse(json.dumps(context, ensure_ascii=False),
                        content_type="application/json charset=utf-8")  # 返回结果必须是json格式


def plot(request):
    type = list(dict(six.iterlists(request.GET)).keys())[0]
    # item = dict(six.iterlists(request.GET)).keys()
    print('===============', type, '==================')

    if type == 'Combine':
        chart = echarts_barline(DF, x_feature, y_feature, box)
    elif type == 'Line':
        chart = echarts_myline(DF, x_feature, y_feature, box)
    elif type == 'Stack':
        chart = echarts_stackbar(DF, x_feature, y_feature, box)

    elif type == 'Plot':
        chart = page_simple_layout()
        # chart = echarts_two_test(query1_data, process_choose)

    chart = chart.dump_options()

    total_trend = json.loads(chart)
    # print('total_trend', type(total_trend))
    context = {
        'total_trend': total_trend,
    }
    return HttpResponse(json.dumps(context, ensure_ascii=False),
                        content_type="application/json charset=utf-8")


def blog(request):
    mselect_dict = {}
    form_dict = dict(six.iterlists(request.GET))
    df = DF.iloc[0:50]
    dct = columns2dictionary(df)
    for key, value in dct.items():
        mselect_dict[key] = {}

visual/templates/alert/alert.html
{% extends "alert/base.html" %}
<!-- 隐藏分隔条 -->
<div class="ui hidden divider"></div>
{% block body %}

<!-- 不用循环写表格的方法，多个需要手动循环 -->
<!--<table class="ui collapsing table">-->
<!--  <thead>-->
<!--    <tr>-->
<!--        <th colspan="7">-->
<!--            Magnetic-->
<!--        </th>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <th>raw_index</th>-->
<!--      <th>wafernum</th>-->
<!--      <th>Product</th>-->
<!--      <th>HDD_Model</th>-->
<!--      <th>Head_Site</th>-->
<!--      <th>Disk</th>-->
<!--      <th>parameter_name</th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
<!--    <script>-->
<!--        var data = {{data|safe}};-->
<!--        for (var i = 0; i < data.length; i++) {-->
<!--            document.write(`-->
<!--              <tr>-->
<!--                <td width="100">${data[i].raw_index}</td>-->
<!--                <td width="100">${data[i].wafernum}</td>-->
<!--                <td width="100">${data[i].Product}</td>-->
<!--                <td width="100">${data[i].HDD_Model}</td>-->
<!--                <td width="100">${data[i].Head_Site}</td>-->
<!--                <td width="100">${data[i].Disk}</td>-->
<!--                <td width="100">${data[i].parameter_name}</td>-->
<!--              </tr>-->
<!--            `);-->
<!--        }-->
<!--    </script>-->
<!--  </tbody>-->
<!--</table>-->

<h3 class="ui center aligned header">Outlier Alert</h3>
<div class="ui two column stackable grid container">
    {% for key,value in data.items %}
        <div class="column">
            <div class="ui segment">
                <details>
                    <summary>
                        {{ key }}
                    </summary>
                    <p>

                        <table class="ui collapsing table">
                            <tr>
                              <td>wafernum</td>
                              <td>feature</td>
                              <td>value</td>
                              <td>hdd_model</td>
                            </tr>
                        {% for i in value %}
                              <tr>
                                  <td width="20">{{i.wafernum}}</td>
                                  <td width="20">{{i.feature}}</td>
                                  <td width="20">{{i.value}}</td>
                                  <td width="20">{{i.hdd_model}}</td>
                              </tr>
                        {% endfor %}
                        </table>
                    </p>
                </details>
            </div>
        </div>
    {% endfor %}
</div>

<!--<script>-->
<!--    var dic = {{data|safe}};-->
<!--    for (var key in dic) {-->
<!--        document.write('<table class="ui collapsing table">');-->
<!--        document.write(`-->
<!--            <thead>-->
<!--                <tr>-->
<!--                    <th colspan="4">-->
<!--                        ${key}-->
<!--                    </th>-->
<!--                </tr>-->
<!--            </thead>-->
<!--            <tr>-->
<!--              <td>wafernum</td>-->
<!--              <td>feature</td>-->
<!--              <td>value</td>-->
<!--              <td>hdd_model</td>-->
<!--            </tr>-->
<!--        `);-->
<!--        for (var i = 0; i < dic[key].length; i++) {-->
<!--            document.write(`-->
<!--                 <tr>-->
<!--                    <td width="20">${dic[key][i].wafernum}</td>-->
<!--                    <td width="20">${dic[key][i].feature}</td>-->
<!--                    <td width="20">${dic[key][i].value}</td>-->
<!--                    <td width="20">${dic[key][i].hdd_model}</td>-->
<!--                  </tr>-->
<!--            `);-->
<!--        }-->
<!--        document.write('</table>');-->
<!--    }-->
<!--</script>-->

<div class="ui form">
    <form action="/visual/index" method="post">
        {% csrf_token %}
<!--        <div class="ui buttons">-->
<!--            <input class="ui blue button" type='button' id='to_index' value="跳转画图"/>-->
<!--        </div>-->

        <div class="row" style="text-align: center;margin-top: 30px;">
            <button class="ui positive basic button">画图</button>
        </div>
    </form>
</div>

<script type="text/javascript">
    $("#to_index").click(function (event){
        event.preventDefault();
        var form_data = {
            "D_MULTI_SELECT": $("#D_MULTI_SELECT").val(),

        };
        $.ajax({
            url: '{% url 'visual:index' %}',
            type: 'GET',
            data: form_data,
            success: function(ret) {
                $("#D_MULTI_SELECT").html(ret['D_MULTI_SELECT'])
            },
            error: function() {
                console.log('failure')
            }
        });
    })
</script>
{% endblock body %}

visual/templates/alert/base.html
<!-- 载入静态文件 更早版本可能会用load staticfiles -->
{% load static %}
<!--<!DOCTYPE html>-->
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <title>数据分析</title>
    <link rel="stylesheet" href="{% static 'datatables/dataTables.semanticui.min.css' %}">
    <link rel="stylesheet" href="{% static 'Semantic-UI-CSS-master/semantic.min.css' %}">
    <script src="{% static 'jquery/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'datatables/dataTables.semanticui.min.js' %}"></script>
    <!-- <script src="{% static 'datatables/percentageBars.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'Semantic-UI-CSS-master/semantic.js' %}"></script>
    <script src="{% static 'echarts/echarts.min.js' %}"></script>
    <!-- <script src="{% static 'echarts/china.js' %}"></script> -->
</head>



<body>

<!-- 引入导航栏 -->
{% include 'alert/header.html' %}
<!-- 预留具体页面的位置 -->
{% block body %}{% endblock body %}
<!-- 引入注脚 -->
<!--{% include 'visual/footer.html' %}-->

</body>

</html>

visual/templates/alert/demo.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->

<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>操作元素-新浪下拉菜单</title>-->
<!--    <style>-->
<!--        * {-->
<!--            margin: 0;-->
<!--            padding: 0;-->
<!--            box-sizing: border-box;-->
<!--        }-->

<!--        ul li {-->
<!--            list-style: none;-->
<!--        }-->

<!--        a {-->
<!--            text-decoration: none;-->
<!--            color: #4c4c4c;-->
<!--        }-->

<!--        a:hover {-->
<!--            color: #e88415;-->
<!--        }-->

<!--        .box {-->
<!--            width: 80px;-->
<!--            margin: 50px auto;-->
<!--            font-size: 14px;-->
<!--            color: #4c4c4c;-->
<!--        }-->

<!--        .weibo {-->
<!--            position: relative;-->
<!--            background-color: #fcfcfc;-->
<!--        }-->

<!--        .weibo a {-->
<!--            display: block;-->
<!--            height: 40px;-->
<!--            line-height: 40px;-->
<!--            padding-left: 20px;-->
<!--        }-->

<!--        .change {-->
<!--            color: #f9a74f;-->
<!--            background-color: #edeef0;-->
<!--        }-->

<!--        i {-->
<!--            position: absolute;-->
<!--            top: 50%;-->
<!--            right: 15px;-->
<!--            margin-top: -4px;-->
<!--            width: 5px;-->
<!--            height: 5px;-->
<!--            border-bottom: 1px solid orangered;-->
<!--            border-right: 1px solid orangered;-->
<!--            transform: rotate(45deg);-->
<!--        }-->

<!--        .weiboList {-->
<!--            display: none;-->
<!--        }-->

<!--        .weiboList li a {-->
<!--            display: block;-->
<!--            width: 80px;-->
<!--            height: 33px;-->
<!--            line-height: 33px;-->
<!--            padding-left: 15px;-->
<!--            border-bottom: 1px solid #fecc5b;-->
<!--            background-color: #fff;-->
<!--        }-->

<!--        .weiboList li a:hover {-->
<!--            background-color: #fff5da;-->
<!--        }-->
<!--    </style>-->
<!--</head>-->

<!--<body>-->
<!--    <div class="box">-->
<!--        <div class="weibo"><a href="#" >微博<i class="select"></i></a></div>-->
<!--        <ul class="weiboList">-->
<!--            <li><a href="#" >私信</a></li>-->
<!--            <li><a href="#" >评论</a></li>-->
<!--            <li><a href="#" >@我</a></li>-->
<!--        </ul>-->
<!--    </div>-->

<!--    <script>-->
<!--        var box = document.querySelector('.box');-->
<!--        var weibo = document.querySelector('.weibo');-->
<!--        var weiboList = document.querySelector('.weiboList');-->

<!--        box.onmouseover = function() {-->
<!--            weibo.className = 'weibo change'-->
<!--            weiboList.style.display = 'block';-->

<!--        }-->

<!--        box.onmouseout = function() {-->
<!--            weibo.className = 'weibo';-->
<!--            weiboList.style.display = 'none';-->
<!--        }-->
<!--    </script>-->
<!--</body>-->

<!--</html>-->

visual/templates/alert/header.html
<div class="ui inverted menu">
<!-- <div class="ui pointing menu"> -->
    <div class="ui container">
        <a class="red item" data-tab="HomePage" href={% url 'visual:alert' %} >&nbsp;&nbsp;&nbsp;&nbsp;警报信息 AlertPage&nbsp;&nbsp;&nbsp;&nbsp;</a>
        <a class="orange item" data-tab="Algorithm" href={% url 'visual:overview' %} >&nbsp;&nbsp;&nbsp;&nbsp;数据总览 Overview&nbsp;&nbsp;&nbsp;&nbsp;</a>
    </div>
</div>

<!-- <div class="ui pointing secondary menu">
    <a class="item" data-tab="Plot"><i class="circle icon"></i>Plot</a>
    <a class="item active" data-tab="Summary"><i class="circle icon"></i>Summary</a>
    <a class="item" data-tab="Analysis"><i class="circle icon"></i>Analysis</a>
</div> -->